version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_sbspost
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./src/static:/static
    ports:
      - '7000:80'
    depends_on:
      - django
  django:
    build: ./django
    container_name: django_sbspost
    expose:
      - '8001'
    volumes:
      - ./src:/code
    command: uwsgi --socket :8001 --module postingprj.wsgi
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db_sbspost
    volumes:
      - ./db/dbdata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      - POSTGRES_USER=sbs
      - POSTGRES_PASSWORD=sbsgakuen
      - POSTGRES_DB=postingDB

